-- Core user-generated application data. Run after schema.sql.
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null default '',
  bio text not null default '',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.reviews (
  id bigint generated by default as identity primary key,
  amenity_id bigint not null references public.amenities(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  review_text text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (amenity_id, user_id)
);

create table public.review_votes (
  review_id bigint not null references public.reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  value smallint not null check (value in (-1, 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (review_id, user_id)
);

create table public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  amenity_id bigint not null references public.amenities(id) on delete cascade,
  notify_on_updates boolean not null default true,
  created_at timestamptz not null default now(),
  primary key (user_id, amenity_id)
);

create index reviews_amenity_created_idx on public.reviews (amenity_id, created_at desc);
create index favorites_user_created_idx on public.favorites (user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.reviews enable row level security;
alter table public.review_votes enable row level security;
alter table public.favorites enable row level security;

create policy "profiles are publicly readable" on public.profiles for select to anon, authenticated using (true);
create policy "users manage own profile" on public.profiles for all to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "reviews are publicly readable" on public.reviews for select to anon, authenticated using (true);
create policy "users create own reviews" on public.reviews for insert to authenticated with check (auth.uid() = user_id);
create policy "users update own reviews" on public.reviews for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users delete own reviews" on public.reviews for delete to authenticated using (auth.uid() = user_id);
create policy "votes are publicly readable" on public.review_votes for select to anon, authenticated using (true);
create policy "users manage own votes" on public.review_votes for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own favorites" on public.favorites for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.create_profile()
returns trigger language plpgsql security definer set search_path = public
as $$ begin insert into public.profiles (id) values (new.id); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.create_profile();
