create table public.chats (
  id bigint generated by default as identity primary key,
  chat_type text not null default 'direct' check (chat_type in ('direct','group','amenity_forum')),
  amenity_id bigint references public.amenities(id) on delete set null,
  name text not null default '',
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chat_participants (
  chat_id bigint not null references public.chats(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz,
  primary key (chat_id, user_id)
);

create table public.messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.chats(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 5000),
  created_at timestamptz not null default now()
);

create index messages_chat_created_idx on public.messages(chat_id, created_at);
alter table public.chats enable row level security;
alter table public.chat_participants enable row level security;
alter table public.messages enable row level security;

create policy "participants can read chats" on public.chats for select to authenticated using (exists (select 1 from public.chat_participants p where p.chat_id = chats.id and p.user_id = auth.uid()));
create policy "users can create chats" on public.chats for insert to authenticated with check (created_by = auth.uid());
create policy "participants can read membership" on public.chat_participants for select to authenticated using (user_id = auth.uid() or exists (select 1 from public.chat_participants p where p.chat_id = chat_participants.chat_id and p.user_id = auth.uid()));
create policy "users can join created chats" on public.chat_participants for insert to authenticated with check (user_id = auth.uid() or exists (select 1 from public.chats c where c.id = chat_id and c.created_by = auth.uid()));
create policy "participants can read messages" on public.messages for select to authenticated using (exists (select 1 from public.chat_participants p where p.chat_id = messages.chat_id and p.user_id = auth.uid()));
create policy "participants can send messages" on public.messages for insert to authenticated with check (sender_id = auth.uid() and exists (select 1 from public.chat_participants p where p.chat_id = messages.chat_id and p.user_id = auth.uid()));
