create table public.food_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  donor_id uuid references auth.users(id) on delete set null,
  donation_code text not null unique,
  latitude double precision not null,
  longitude double precision not null,
  status text not null default 'active' check (status in ('active','pending_confirmation','fulfilled','cancelled','expired')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '4 hours'),
  claimed_at timestamptz,
  fulfilled_at timestamptz
);
create table public.food_donations (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.food_requests(id),
  requester_id uuid references auth.users(id) on delete set null,
  donor_id uuid references auth.users(id) on delete set null,
  solana_tx_signature text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now()
);
create index food_requests_active_idx on public.food_requests(status, expires_at);
alter table public.food_requests enable row level security;
alter table public.food_donations enable row level security;
create policy "users can read active food requests" on public.food_requests for select to authenticated using (expires_at > now() and (status = 'active' or requester_id = auth.uid() or donor_id = auth.uid()));
create policy "users create own food requests" on public.food_requests for insert to authenticated with check (requester_id = auth.uid());
create policy "participants update food requests" on public.food_requests for update to authenticated using (requester_id = auth.uid() or donor_id = auth.uid()) with check (requester_id = auth.uid() or donor_id = auth.uid());
create policy "participants read donations" on public.food_donations for select to authenticated using (requester_id = auth.uid() or donor_id = auth.uid());
create or replace function public.claim_food_request(p_request_id bigint, p_donor_id uuid)
returns public.food_requests language plpgsql security definer set search_path = public
as $$ declare result public.food_requests; begin update public.food_requests set donor_id=p_donor_id,status='pending_confirmation',claimed_at=now() where id=p_request_id and status='active' and expires_at>now() and requester_id<>p_donor_id returning * into result; if result.id is null then raise exception 'Request is unavailable'; end if; return result; end; $$;
grant execute on function public.claim_food_request(bigint,uuid) to authenticated;
