-- Initial relational schema for the Cloudflare rewrite.
-- Run in Supabase SQL Editor, then add stricter policies before production use.

create table public.amenity_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text not null default '',
  color text not null default '#3388ff',
  parent_id bigint references public.amenity_types(id) on delete set null
);

create table public.amenities (
  id bigint generated by default as identity primary key,
  external_id text not null default '',
  amenity_type_id bigint not null references public.amenity_types(id) on delete cascade,
  name text not null,
  latitude double precision not null,
  longitude double precision not null,
  address text,
  prop_name text not null default '',
  description text not null default '',
  operator text not null default '',
  hours_of_operation jsonb not null default '{}'::jsonb,
  is_open_24hrs boolean not null default false,
  accessibility text not null default '',
  active boolean not null default true,
  seasonal boolean not null default false,
  source text not null default '',
  raw_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (amenity_type_id, external_id)
);

create index amenities_location_idx on public.amenities (latitude, longitude);
create index amenities_active_type_idx on public.amenities (active, amenity_type_id);

create table public.availability_reports (
  id bigint generated by default as identity primary key,
  amenity_id bigint not null references public.amenities(id) on delete cascade,
  is_available boolean not null,
  session_key text not null default '',
  reported_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '48 hours')
);

alter table public.amenity_types enable row level security;
alter table public.amenities enable row level security;
alter table public.availability_reports enable row level security;

create policy "public can read active amenities" on public.amenities
  for select to anon, authenticated using (active = true);
create policy "public can read amenity types" on public.amenity_types
  for select to anon, authenticated using (true);
create policy "anyone can read recent availability" on public.availability_reports
  for select to anon, authenticated using (expires_at > now());
create policy "anyone can report availability" on public.availability_reports
  for insert to anon, authenticated with check (true);
-- Availability inserts will be moved behind a Pages Function once auth/session
-- behavior is implemented; do not grant anonymous inserts by default.
