import { createClient } from "@supabase/supabase-js";
import fs from "node:fs";
type R=Record<string,any>; type A={type_name:string;source:string;external_id:string;name:string;latitude:number;longitude:number;raw_data:R;address?:string;description?:string;operator?:string;active?:boolean;accessibility?:string;hours_of_operation?:R};
function load(){try{for(const l of fs.readFileSync("../.env.postgres","utf8").split(/\r?\n/)){const m=l.match(/^([^=#]+)=(.*)$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^['"]|['"]$/g,"")}}catch{}}
async function get(id:string,top=100000){const u=new URL(`https://data.cityofnewyork.us/api/odata/v4/${id}`);u.search=new URLSearchParams({"$top":String(top),"$format":"json"}).toString();const r=await fetch(u);if(!r.ok)throw Error(`${id}: ${r.status}`);return(await r.json() as R).value as R[]}
function point(g:any){const c=g?.coordinates;if(!Array.isArray(c))return null;const p=[Number(c[1]),Number(c[0])] as [number,number];return p.every(Number.isFinite)?p:null}
function make(t:string,s:string,id:any,n:any,p:[number,number],raw:R,x:Partial<A>={}):A|null{return id?{type_name:t,source:s,external_id:String(id),name:String(n||t).slice(0,200),latitude:p[0],longitude:p[1],raw_data:raw,...x}:null}
async function simple(id:string,top:number,fn:(x:R,p:[number,number])=>A|null){const out:A[]=[];for(const x of await get(id,top)){const p=point(x.the_geom||x.location_1)||(x.x!=null&&x.y!=null?[Number(x.y),Number(x.x)]:null);if(p){const a=fn(x,p);if(a)out.push(a)}}return out}
const fountains=()=>simple("qnv7-p7a2",10000,(x,p)=>make("Water Fountain","nyc_water_fountains",x.system||x._id||x.ID,x.Location||x.location,p,x,{address:x.propertyna||"",description:x.Position||""}));
const restrooms=()=>simple("i7jb-7jku",10000,(x,p)=>make("Restroom","nyc_public_restrooms",x.__id||`${p[0]}_${p[1]}`,x.facility_name,p,x,{address:x.location_type||"",description:x.additional_notes||"",operator:x.operator||"",active:String(x.status||"").toLowerCase()==="operational",accessibility:x.accessibility||"",hours_of_operation:{raw:x.hours_of_operation||""}}));
const racks=()=>simple("592z-n7dk",100000,(x,p)=>make("Bike Rack","nyc_bike_racks",x.site_id||`${p[0]}_${p[1]}`,x.ntaname||x.ifoaddress,p,x,{address:x.ifoaddress||"",description:`Type: ${x.racktype||"Standard Rack"}`}));
const cooling=()=>simple("h2bn-gu9k",5000,(x,p)=>make(String(x.featuretype||"Cooling Site"),"nyc_cooling_sites",x.__id,x.propertyname||"Cooling Site",p,x,{address:x.subpropertyname||"",active:String(x.status||"").toLowerCase()==="activated"}));
async function linknyc(){const out:A[]=[];for(const x of await get("yjub-udmw")){const provider=String(x.provider||""),id=String(x.sourceid||"");if(!provider.toLowerCase().includes("linknyc")&&!id.toUpperCase().startsWith("LINK-"))continue;const p=point(x.location_lat_long)||[Number(x.latitude),Number(x.longitude)] as [number,number];if(!p.every(Number.isFinite))continue;const a=make("LinkNYC Kiosk","nyc_linknyc",`linknyc:${id||`${p[0]}:${p[1]}`}`,id?`LinkNYC ${id}`:"LinkNYC Kiosk",p,x,{address:[x.location,x.city,x.boroname].filter(Boolean).join(", "),operator:provider,description:[provider&&`Provider: ${provider}`,x.ssid&&`SSID: ${x.ssid}`,x.remarks&&`Remarks: ${x.remarks}`].filter(Boolean).join(" | ")});if(a)out.push(a)}return out}
const sources:Record<string,()=>Promise<A[]>>={fountains,restrooms,"bike-racks":racks,"cooling-sites":cooling,linknyc};
async function main(){load();const raw=process.env.SUPABASE_URL||process.env.DATABASE_API,key=process.env.SUPABASE_SECRET_KEY||process.env.SERVICE_ROLE_KEY||process.env.PUBLISHABLE_DB_KEY;if(!raw||!key)throw Error("Set DATABASE_API and SUPABASE_SECRET_KEY");const db=createClient(raw.replace(/\/rest\/v1\/?$/, ""),key);const selected=process.argv.slice(2).flatMap(x=>x==="all"?Object.keys(sources):[x]);for(const name of selected.length?selected:Object.keys(sources)){const rows=await sources[name](),types=[...new Set(rows.map(x=>x.type_name))],t=await db.from("amenity_types").upsert(types.map(name=>({name,color:name==="LinkNYC Kiosk"?"#4CAF50":"#3388ff",icon:name==="LinkNYC Kiosk"?"wifi":""})),{onConflict:"name"}).select("id,name");if(t.error)throw t.error;const ids=new Map((t.data||[]).map(x=>[x.name,x.id])),payload=rows.map(x=>({external_id:x.external_id,amenity_type_id:ids.get(x.type_name),name:x.name,latitude:x.latitude,longitude:x.longitude,address:x.address||"",description:x.description||"",operator:x.operator||"",hours_of_operation:x.hours_of_operation||{},accessibility:x.accessibility||"",active:x.active??true,source:x.source,raw_data:x.raw_data}));for(let i=0;i<payload.length;i+=500){const r=await db.from("amenities").upsert(payload.slice(i,i+500),{onConflict:"amenity_type_id,external_id"});if(r.error)throw r.error}console.log(`${name}: upserted ${rows.length}`)}}
main().catch(e=>{console.error(e);process.exitCode=1});
